name: Cocotb CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator make
          python3 -m pip install --upgrade pip
          python3 -m pip install cocotb
      - name: Run Cocotb tests
        run: |
          ./run.sh
